### ISSUE TITLE
fix setup.py

### ISSUE THREAD

**Issue by Eloitor** [joanisc/loyaltyCardsOpen#11]
Hi, I'm trying to package loyaltyCardsOpen to alpine linux (for postmarketOS). When downloading the source from https://github.com/joanisc/loyaltyCardsOpen/archive/refs/tags/v0.1.6.tar.gz and running `python3 setup.py build` I get the following error

```
error: Multiple top-level packages discovered in a flat-layout: ['css', 'tmp'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.
```

Thank you for this project, I think it could be a useful app.

**Comment by joanisc** [comment]
Thank you for the issue. I don't know if there is any other way to do what you want. Because I think my setup.py is not updated and not working properly... I'll take a look. I did a change in last commit to fix your error. But I have doubts that it works the build for you.

**Comment by Eloitor** [comment]
It works, here is my output:

```
$ python3 setup.py build
running build
running build_scripts
creating build
creating build/scripts-3.11
copying and adjusting loyaltyCards.py -> build/scripts-3.11
changing mode of build/scripts-3.11/loyaltyCards.py from 644 to 755
```

Thank you for the fast response

**Comment by joanisc** [comment]
But it is the app working with this build?

**Comment by Eloitor** [comment]
It runs well in the source folder, but I'm not able to install it in `/usr` ...

To install the package (after the package is build using `python3 setup.py build`) I run:
`python3 setup.py install --prefix=/usr --root="$pkgdir"`

I think that this is ignored since the path seems to be hardcoded here: https://github.com/joanisc/loyaltyCardsOpen/blob/master/loyaltyCards.py#L16-L22

**Comment by Eloitor** [comment]
By the way I think that the database should be placed in the `$HOME` directory, in `$XDG_DATA_HOME/loyaltycardsopen/`  or in `$HOME/.local/share/loyaltycardsopen/` if `$XDG_DATA_HOME` is not set.

**Comment by joanisc** [comment]
You are right Eloi. It is hardcoded. And yes, your proposal sounds fine. I've never before heart about $XDG_DATA_HOME but it makes sense. I think I should take a review on the app and check the paths, the setup.py and more... I'm not using the Pinephone anymore and with littte time lately so the app is a bit outdated.

**Comment by Eloitor** [comment]
This might be useful: https://pypi.org/project/xdg or https://pypi.org/project/xdgenvpy

**Comment by joanisc** [comment]
I think I have corrected the **setup.py** and the path issues and now you should be able to package loyaltyCardsOpen to alpine linux/postmarketOS. 

For now, for simplicity and easy removal. I have not move the db to the user folder as you suggested. I'll take a look on this in the future maybe.
