### ISSUE TITLE
Some problems with installation

### ISSUE THREAD

**Issue by AndyM48** [joanisc/loyaltyCardsOpen#3]
Thank you for creating this much needed app. However I have had a couple of problems installing and using it

Firstly I think that there should be an installation script. For example the Shell script could be installed in /usr/bin, the desktop file in /usr/share/applications, the icon file in /usr/share/pixmaps, the python scripts in /usr/share /loyaltyCardsOpen and finally the user files (database and config)  in ~/.config/loyaltyCardsOpen.

Secondly I presume that the Entry of the loyalty card number will generate a bar code. I could not check this because the entry will not save without a photo of the front and the back of the card. If the bar code is available then the photos are not actually essential, and the entry should be saved without them.

**Comment by chookity-pokk** [comment]
For what it's worth, there is a deb file that can be found in the link below. I do agree though that there could be an install script, I'll try and write one up today.

https://github.com/joanisc/loyaltyCardsOpen/releases/tag/v0.1.5

**Comment by joanisc** [comment]
Thank you for your comments @fdservices ! 
Yes! It's a good idea to do an script. I will take a look if I have some time and if @ragreenburg is not faster. And for sure I'll try to do the generation of a bar code too. No results guaranteed but I'll try. When achieved, as you said it would be not necessary to make the photos mandatory.

**Comment by chookity-pokk** [comment]
I have an open pull request for the installation part of this now.

**Comment by AndyM48** [comment]
@joanisc Not tested but this may work:
`$  barcode -S -b 325039000057548081 -o barcode.svg`

**Comment by joanisc** [comment]
Thank you @fdservices . I did it with python-barcode and It should already work for EAN13 barcodes. A more deph implementation needed to select the kind of barcode from the cards entry screen. Just a first approach now. Not updated the deb file, but I would do if I have some time in other moment. I will pursue the installation script too on other moment...

**Comment by AndyM48** [comment]
I would be surprised if all the loyalty cards did not use the same encoding. Have you tested this with a scanner? I can probably pursued one of our merchants to try it if you can update the code.

Thank you

**Comment by AndyM48** [comment]
Incidentally I suspect that you will need a 128? type. But we will have to suck it and see. :-)

**Comment by AndyM48** [comment]
If I install python-barcode with pip it is installed to ~/.local/bin whereas I would have thought it should be installed to /usr/bin.

The "install script" only installs a .desktop file to ~/.local/share/applications.

> For example the Shell script could be installed in /usr/bin, the desktop file in /usr/share/applications, the icon file in /usr/share/pixmaps, the python scripts in /usr/share/loyaltyCardsOpen and finally the user files (database and config) in ~/.config/loyaltyCardsOpen.

This scheme installs the software globally with the specific  user files located in their home directory. There are only some minor changes required to the code:

-  point the shell script to /usr/share/loyaltyCardsOpen/loyaltyCards.py 

- and, for the local files, save the location $HOME/.config/loyaltyCardsOpen, create the folder if it does not exist, with a default .conf and .db file, and use that path to access those files.

The original desktop file would now be correct.

**Comment by AndyM48** [comment]
Barcodes do not work for all my cards. ean13 is for 13 digit codes only. A quick check shows that my cards have either 13 and 19 digits, so the 19 digit cards will need a different type. The barcode programme tries to automatically chose the best type. ean13 for 13 digits, 128b for 19 digits. I don't know if there are any other types used by storecards.

**Comment by joanisc** [comment]
You are right and I know what you say @fdservices . More work is needed for other barcodes types and for the installation script also. I would continue improving this things on my free time, not really much these days. Thank you for your suggestions! By the way if you have time and know how to improve something pull requests are welcome. :-). Not integration promised but if they work and help probably.

**Comment by AndyM48** [comment]
Hmmm - I submitted a pull request to add install and uninstall scripts.

I am not sure that python-barcode supports 128b types, if indeed that is required. The project page only says code128 which is not the same. However there are other scripts on google that will apparently do it.
